---
# solutions/2/guestbook.yml: How to install the guestbook application.
# 2014 June 18


- name: install guestbook play
  hosts: guestbook
  user: root

  tasks:
  - name: get packages
    yum: pkg={{ item }} state=latest
    with_items:
      - php
      - httpd

  - name: get guestbook application
    get_url: url=https://github.com/pgwillia/guestbook/archive/v1.0.tar.gz dest=/tmp/guestbook-1.0.tar.gz
  - name: create /var/www/sites
    file: state=directory path=/var/www/sites owner=apache group=apache 
  - name: unpack guestbook application
    unarchive: src=/tmp/guestbook-1.0.tar.gz dest=/var/www/sites/ copy=no
  - name: link application to httpd html 
    file: state=link src=/var/www/sites/guestbook-1.0/{{ item }} dest=/var/www/html/{{ item }}
    with_items:
      - add_entry.php
      - file.php
      - get_entries.php
      - guestbook.php
  - name: allow apache to write to /var/www/html
    file: path=/var/www/html owner=apache group=apache

  - name: start httpd
    service: name=httpd state=started enabled=yes
